/// WARNING: Generated code
/// This class can be generated by ONOMirror >> #OstDomainSelectorIndicesCppClass 
///
/// Do not modifiy manually, needs to be in sync with the image

class OstDomainSelector_Indices {
public:
  static const oop_int_t AdoptObject_ = 0;
  static const oop_int_t DomainForNewObjects = 1;
  static const oop_int_t EvaluateInContext_ = 2;
  static const oop_int_t EvaluateInContextOnBaseLevel_ = 3;
  static const oop_int_t Initialize = 4;
  static const oop_int_t NewProcessFor_ = 5;
  static const oop_int_t PrimAt_On_ = 6;
  static const oop_int_t PrimAt_On_Put_ = 7;
  static const oop_int_t PrimBasicAt_On_ = 8;
  static const oop_int_t PrimBasicAt_On_Put_ = 9;
  static const oop_int_t PrimInstVarAt_On_ = 10;
  static const oop_int_t PrimInstVarAt_On_Put_ = 11;
  static const oop_int_t PrimShallowCopy_ = 12;
  static const oop_int_t ReadField_Of_ = 13;
  static const oop_int_t ReadGlobal_ = 14;
  static const oop_int_t RequestExecution_Of_On_ = 15;
  static const oop_int_t RequestExecution_With_Of_On_ = 16;
  static const oop_int_t RequestExecution_With_With_Of_On_ = 17;
  static const oop_int_t RequestExecution_With_With_With_Of_On_ = 18;
  static const oop_int_t RequestExecution_With_With_With_With_Of_On_ = 19;
  static const oop_int_t RequestExecution_With_With_With_With_With_Of_On_ = 20;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_Of_On_ = 21;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_Of_On_ = 22;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_With_Of_On_ = 23;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_With_With_Of_On_ = 24;
  static const oop_int_t RequestExecutionOf_On_ = 25;
  static const oop_int_t RequestExecutionOf_With_Lookup_On_ = 26;
  static const oop_int_t SpawnHere_ = 27;
  static const oop_int_t Write_ToField_Of_ = 28;
  static const oop_int_t WriteGlobal_Value_ = 29;
  
};

