/// WARNING: Generated code
/// This class can be generated by ONOMirror >> #OstDomainSelectorIndicesCppClass 
///
/// Do not modifiy manually, needs to be in sync with the image

class OstDomainSelector_Indices {
public:
  static const oop_int_t PrimAt_On_                                                   = 0;
  static const oop_int_t PrimAt_On_Put_                                               = 1;
  static const oop_int_t PrimBasicAt_On_                                              = 2;
  static const oop_int_t PrimBasicAt_On_Put_                                          = 3;
  static const oop_int_t PrimInstVarAt_On_                                            = 4;
  static const oop_int_t PrimInstVarAt_On_Put_                                        = 5;
  static const oop_int_t PrimNext_                                                    = 6;
  static const oop_int_t PrimNext_Put_                                                = 7;
  static const oop_int_t PrimReplaceFrom_To_With_StartingAt_On_                       = 8;
  static const oop_int_t PrimShallowCopy_                                             = 9;
  static const oop_int_t ReadField_Of_                                                = 10;
  static const oop_int_t ReadLiteral_                                                 = 11;
  static const oop_int_t RequestExecution_Of_On_                                      = 12;
  static const oop_int_t RequestExecution_With_Of_On_                                 = 13;
  static const oop_int_t RequestExecution_With_With_Of_On_                            = 14;
  static const oop_int_t RequestExecution_With_With_With_Of_On_                       = 15;
  static const oop_int_t RequestExecution_With_With_With_With_Of_On_                  = 16;
  static const oop_int_t RequestExecution_With_With_With_With_With_Of_On_             = 17;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_Of_On_        = 18;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_Of_On_   = 19;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_With_Of_On_ = 20;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_With_With_Of_On_ = 21;
  static const oop_int_t RequestExecutionOf_On_                                       = 22;
  static const oop_int_t RequestExecutionOf_With_Lookup_On_                           = 23;
  static const oop_int_t Write_ToField_Of_                                            = 24;
  static const oop_int_t Write_ToField_Of_Return_                                     = 25;
  static const oop_int_t Write_ToLiteral_                                             = 26;
  
  
  
  static const oop_int_t PrimAt_On__Mask                                              = 0x1 << Tag_Size;
  static const oop_int_t PrimAt_On_Put__Mask                                          = 0x2 << Tag_Size;
  static const oop_int_t PrimBasicAt_On__Mask                                         = 0x4 << Tag_Size;
  static const oop_int_t PrimBasicAt_On_Put__Mask                                     = 0x8 << Tag_Size;
  static const oop_int_t PrimInstVarAt_On__Mask                                       = 0x10 << Tag_Size;
  static const oop_int_t PrimInstVarAt_On_Put__Mask                                   = 0x20 << Tag_Size;
  static const oop_int_t PrimNext__Mask                                               = 0x40 << Tag_Size;
  static const oop_int_t PrimNext_Put__Mask                                           = 0x80 << Tag_Size;
  static const oop_int_t PrimReplaceFrom_To_With_StartingAt_On__Mask                  = 0x100 << Tag_Size;
  static const oop_int_t PrimShallowCopy__Mask                                        = 0x200 << Tag_Size;
  static const oop_int_t ReadField_Of__Mask                                           = 0x400 << Tag_Size;
  static const oop_int_t ReadLiteral__Mask                                            = 0x800 << Tag_Size;
  static const oop_int_t RequestExecution_Of_On__Mask                                 = 0x1000 << Tag_Size;
  static const oop_int_t RequestExecution_With_Of_On__Mask                            = 0x2000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_Of_On__Mask                       = 0x4000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_Of_On__Mask                  = 0x8000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_With_Of_On__Mask             = 0x10000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_With_With_Of_On__Mask        = 0x20000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_Of_On__Mask   = 0x40000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_Of_On__Mask = 0x80000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_With_Of_On__Mask = 0x100000 << Tag_Size;
  static const oop_int_t RequestExecution_With_With_With_With_With_With_With_With_With_Of_On__Mask = 0x200000 << Tag_Size;
  static const oop_int_t RequestExecutionOf_On__Mask                                  = 0x400000 << Tag_Size;
  static const oop_int_t RequestExecutionOf_With_Lookup_On__Mask                      = 0x800000 << Tag_Size;
  static const oop_int_t Write_ToField_Of__Mask                                       = 0x1000000 << Tag_Size;
  static const oop_int_t Write_ToField_Of_Return__Mask                                = 0x2000000 << Tag_Size;
  static const oop_int_t Write_ToLiteral__Mask                                        = 0x4000000 << Tag_Size;
  
  
  /** Make it easier to identify whether any of them is customize.
   Remember that it's a SmallInt and we need to shift by the Tag_Bit */
  static const oop_int_t RequestExecutionMask = 0xFFF000 << Tag_Size;
  static const oop_int_t WriteToFieldMask     = 0x3000000 << Tag_Size;
};



/** Identity Hash: 331B2C12B751E9A3B2474EA009928AE5  **/

